Nazar/feature/api v4
Simple2B/zrosty-hay-be pull request #7
Opened 2024-01-23 14:13 UTC by Nazar-kob

2024-01-23 16:53 UTC, nixissmtp requested changes

2024-01-23 16:53 UTC, nixissmtp commented on api/routes/plant.py
> +        query = query.join(m.PlantFamily).where(m.PlantFamily.type_of == query_params.type_of.value)
why join?

2024-01-23 16:53 UTC, nixissmtp commented on app/models/plant_variety.py
> +    def photo(self) -> str | None:  # type:ignore
WTF is this?

2024-01-23 16:53 UTC, nixissmtp commented on app/models/plant_variety.py
>      _photos: orm.Mapped[List["Photo"]] = orm.relationship(secondary=plant_variety_photo)
make photo write only field

2024-01-23 16:53 UTC, nixissmtp commented on app/schema/plant.py
> +    photo: Photo | None
photos, not photo

2024-01-23 16:53 UTC, nixissmtp commented on docker-compose.staging.yaml
> +    image: simple2b/zrosty-hay:0.1.7
make image version as variable

2024-01-23 20:14 UTC, marynag commented on app/templates/plant_variety/edit_form.html
>              </div>
Add min and max length for textarea

2024-01-23 20:15 UTC, marynag commented on app/templates/plant_variety/edit_form.html
>              <div class="flex items-start mb-6">
Add required attribute
for adding "*" symbol in input label use:
label:has(+ *:required):after,
label:has(~ div *:required):after {
  content: ' *';
  color: red;
}

2024-01-24 09:04 UTC, Nazar-kob commented on docker-compose.staging.yaml
> +    image: simple2b/zrosty-hay:0.1.7
thanks

2024-01-24 10:44 UTC, merged